import Link from 'next/link';
import React from 'react';



const universitiesData = [
    {
        name:"Aga Khan University",
        href:"https://www.aku.edu/Pages/home.aspx",
        text:"Aga Khan University (AKU) in Pakistan is a prominent institution with branches in Karachi and Hyderabad. Known for its excellence in healthcare education, AKU consistently ranks among the top universities globally, particularly in the field of medicine. According to recent rankings, it is placed within the top 500 universities worldwide. AKU is famous for its state-of-the-art facilities, distinguished faculty, and rigorous academic standards. The university is renowned for its medical and nursing programs, which attract students worldwide. The curriculum at AKU is primarily in English, ensuring a broad international reach and facilitating global collaboration. With a strong emphasis on research and community service, AKU continues to make substantial impacts in public health and medical sciences.",
        imageUrl:"/images/aghaKhanUniversity.png"
    },
    {
        name:"Lahore University of Management Sciences",
        href:"",
        text:"Lahore University of Management Sciences (LUMS), located in Lahore, Pakistan, is one of the country's premier higher education institutions. It also has a branch in Karachi, expanding its educational footprint. LUMS is renowned globally, often ranking among the top universities in Asia. It is particularly famous for its rigorous programs in business management and computer science. The institution is well-regarded for producing highly skilled graduates who excel in their respective fields. The curriculum at LUMS is primarily in English, aligning with international standards and enabling students to compete globally. Its strong emphasis on research, innovation, and practical application makes it a sought-after university for aspiring professionals.",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    }, {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    },
    {
        name:"",
        href:"",
        text:"",
        imageUrl:""
    }
]



const Study = () => {
    return (
        <section className=' w-full mt-40'>
        <div className='p-4 md:p-8 gap-y-12 md:gap-y-8'>
            {/* Heading */}
   <Link href="/Study"> <h1 className="text-green-900 font-extrabold text-4xl md:text-7xl text-center">
 Top Universities In Pakistan
    </h1></Link>
    <p className="text-lg mt-12 text-green-950 break-words">Pakistan has universities ranked among the world's top 1000, such as NUST (400), PIEAS (375), LUMS (651-700), and Aga Khan University (201-250). These institutions are known for quality education and research. The Higher Education Commission (HEC) is working to improve educational standards across the country. Education in Pakistan is progressing, with a focus on technology and innovation. These universities play a crucial role in the country's development and offer opportunities for students to excel globally.</p></div></section>
    );
}

export default Study;
